# Generated by Django 5.1.5 on 2025-01-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='health_status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Deceased', 'Deceased')], max_length=10),
        ),
    ]
